packages:
  # - "web"
  - "www"
  # - "editor"
  # - "editor-packages/*"
  # - "apps/*"
  - "apps/backgrounds"
  - "apps/docs"
  - "apps/forms"
  # - "apps/posts"
  - "apps/site"
  - "apps/blog"
  - "packages/*"
  # - "packages/.legacy/*"
  - "packages/lib/*"
  # - "externals/code/packages/*"
  # - "externals/code/code"
  # - "externals/boring/packages/*"
  - "ui/editor-ui/packages/*"
  - "ui/*"
