packages:
  - "app"
  - "web"
  - "www"
  - "editor"
  - "docs-site"
  - "editor-packages/*"
  - "apps/*"
  - "packages/app-*"
  - "packages/core-*"
  - "packages/lib/*"
  - "externals/code/packages/*"
  - "externals/code/code"
  - "externals/boring/packages/*"
  - "ui/editor-ui/packages/*"
  - "ui/*"
