packages:
  - "web"
  - "www"
  - "editor"
  - "editor-packages/*"
  - "apps/*"
  - "packages/*"
  - "packages/.legacy/*"
  - "packages/lib/*"
  - "externals/code/packages/*"
  - "externals/code/code"
  - "externals/boring/packages/*"
  - "ui/editor-ui/packages/*"
  - "ui/*"
